version: '3.8'

services:
  #  web:
  #    build: .
  #    env_file:
  #      - .env
  #    ports:
  #      - "3000:3000"
  #    volumes:
  #      - .:/usr/src/app
  #    command: air ./cmd/main.go -b 0.0.0.0
  db:
    image: postgres:16.1-alpine3.19
    container_name: postgres
    ports:
      - "5437:5432"
    environment:
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
      - POSTGRES_DB=${DB_NAME}
#    volumes:
#      - ./postgres/data:/var/lib/postgresql/data

volumes:
  postgres-db:
